remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: This is a github pages test
author: Matt Spiewak
description: This is just a test.
